name: searchbar_animated_suggestions
description: A Flutter package that provides a search bar with animated suggestions.
version: 0.0.2
license: MIT
homepage: https://github.com/ChandanKumar-Singh/searchbar_auto_animated_suggestion/blob/main/lib/saas/saas.dart

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
