name: searchbar_animated_suggestions
description: A Flutter package that provides a search bar with animated suggestions.
version: 0.0.6
license: MIT
homepage: https://github.com/ChandanKumar-Singh/ChandanKumar-Singh-searchbar_animated_suggestions/blob/main/example/lib/saas/saas.dart
repository: https://github.com/ChandanKumar-Singh/ChandanKumar-Singh-searchbar_animated_suggestions.git
environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
